### PR TITLE
Deprecate this repository

### LINKED ISSUE #9: Is multistream an actual thing?
After reading through the README it seems to me that multistream isn't something that is actually used or implemented. The Go and JS implementations point to multistream-select. Multistream reads like a left-over from earlier multiformat attempts.

Please enlighten me on what this is for and whether it is used or not.

### PR DESCRIPTION
**Pull request by vmx**
multistream is not used at all, hence deprecate this specification.

Closes #9.

### CODE REVIEW

**Comment by raulk** [comment]
I'd much rather clear up the spec in terms of prose (e.g. starting a spec for multistream talking about multicodecs without linking it back to multistream until way later is confusing), terminology and intention; then add a _notice_ at the top communicating that this is not used in this form in IPFS nor libp2p.

I think of this work as a paper: it postulates an idea that people are free to adopt if they want to.

Even if _we_ didn't end up using it as proposed herein in our systems (and arguably that's a cue worth surfacing), it can still be acceptable and inspiring for others to adopt/adapt/build upon.

**Review by raulk — COMMENTED** [review]
I'd much rather clear up the spec in terms of prose (e.g. starting a spec for multistream talking about multicodecs without linking it back to multistream until way later is confusing), terminology and intention; then add a notice at the top communicating that this is not used in this form in IPFS nor libp2p.

I think of this work as a paper: it postulates an idea that people are free to adopt if they want to.

Even if we didn't end up using it as proposed herein in our systems (and arguably that's a cue worth surfacing), it can still be acceptable and inspiring for others to adopt/adapt/build upon.

**Comment by vmx** [comment]
But isn't multistream as we would design it today just "multicodec + binary data"? If yes, then for me it's a single sentence in the multicodec repo rather then a full spec.

**Comment by vmx** [comment]
@raulk I currently don't see anyone cleaning this up.

Could we find agreement that merging this PR is better than what we currently have. I find clear messaging that things are outdated better than having outdated/wrong/misleading information out there.

If there's no strong disagreement, I'll merge this PR in two days.

**Comment by raulk** [comment]
@vmx I’m not in favour of deleting the content here. Just keeping the intellectual work of the past intact and adding the deprecation notice at the top of the README should be enough.

**Comment by vmx** [comment]
@raulk The old version is still under version control.

My problem is that if we keep the current spec, it will still be found, which isn't ideal. The wording is wrong "Multicodecs are self-describing protocol/encoding streams" and also the link to the implementations is wrong (as there are no implementations). So there is the chance to confuse people. I really don't see any benefit in keeping it, other than for historical purpose and I think there version control is good enough.

**Comment by SleeplessByte** [comment]
TBH @raulk, as I am currently building the libs for ruby, this is very confusing for me. I just landed on https://github.com/multiformats/multistream-select which seems to be listing the implementations on this repository. I also just wrote the ruby-multicodec implementation which kinda now sounds like the same thing as multistream as https://github.com/multiformats/multistream/pull/5 was never merged.

The current "intellectual work" seems to be incorrect? Am I missing something?

**Review by Stebalien — CHANGES_REQUESTED** [review]
Let's move the readme to README_OLD.md and replace it with a deprecation notice. We desperately need a multiformats owner to cleanup all this stuff but that seems like the best compromise for now.

**Comment by vmx** [comment]
Thanks @Stebalien for that suggestion, I think that is a good compromise.

@raulk Any objections merging this newly updated PR?

**Review by Stebalien — APPROVED** [review]
This leaves all the context in place and makes it easy to restore.

**Pull request merged**
